tasks:
  - init: sudo chmod u+x init.sh && ./init.sh
  - init: |
      nvm install 14.19.0 && 
      nvm use 14.19.0 &&
      sdk install java 17.0.9-tem &&
      sdk use java 17.0.9-tem &&
      java -version
