server:
  port: 8081  # 1. 포트를 8081로 명확하게 지정했습니다.

spring:
  application:
    name: auth

  # 2. 데이터베이스 연결 설정을 추가했습니다. (필수)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb  # 인-메모리 H2 DB를 사용합니다.
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 DB 테이블을 자동으로 갱신합니다.
    show-sql: true     # 실행되는 SQL 쿼리를 로그로 보여줍니다.
    properties:
      hibernate:
        format_sql: true # SQL 로그를 예쁘게 정렬해줍니다.
  
  cloud:
    stream:
      # 3. Kafka 설정을 프로젝트 예시에 맞춰 단순화했습니다.
      kafka:
        binder:
          brokers: localhost:9092 # 로컬에서 실행할 Kafka 서버 주소입니다.
      bindings:
        # 이벤트 발행(out) 채널 설정입니다.
        event-out:
          destination: miniprojectver  # 이벤트가 발행될 토픽(Topic) 이름입니다.
          contentType: application/json

